name: one

on:
  push:
    branches:
      - main
    paths:
      - "one/**"
  pull_request:
    branches:
      - main
    paths:
      - "one/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pip install -e .
          pytest -rfE --cov=one -s --tb=native -v --cov-report xml --cov-report term-missing:skip-covered one

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: one
