name: two

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "two/**"

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pip install .
          pytest -rfE --cov=two -s --tb=native -v --cov-report xml --cov-append two

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: two
